version: "3.8"

services:
  transportprmbot:
    #image: python:3.10.6-alpine
    container_name: transportprmbot
    restart: unless-stopped
    build: 
      context: ./transportprmbot_new/
      network: host
#    networks:
#      - host
    #command: python3 -m pip install --upgrade pip 
    #command: pip install -r requirements.txt
    #command: python3 -m pip install aiogram==2.25.1
    #command: python3 transportprmbot_new/main.py
    #restart: always
    #volumes:
    #  - type: bind
    #    source: ./transportprmbot_new
    #    target: transportprmbot_new
    networks:
      - transportprmbot-network
    volumes:
      - /transportprmbot_new/:/transportprmbot_new/
    ports:
      - 3001:3001

  mongodb_container:
    image: mongo:latest
    container_name: mongodb_transportprmbot
    restart: unless-stopped
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - transportprmbot-network
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  web_apps:
    container_name: web_apps_transportprmbot
    restart: unless-stopped
    build: 
      context: ./web_apps_transportprmbot/
      network: host
    networks:
      - transportprmbot-network
    volumes:
      - /web_apps_transportprmbot/:/web_apps_transportprmbot/
    ports:
      - 5000:5000

networks:
  transportprmbot-network:
    driver: bridge
