BUS = 'Автобус'
TRAMWAY = 'Трамвай'
TAXI = 'Маршрутное такси'
FAVOURITES = 'Избранное'
HELP = 'Помощь'
TIMETABLE = 'Расписание'
MAPS = 'Карта'
keyboard_user_choice = [BUS,TRAMWAY, TAXI, FAVOURITES, HELP]
keyboard_choice_action = [TIMETABLE, MAPS]